#!/usr/bin/env bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/pre-req-check
cd $DIR/..

$DIR/teardown

set -e

docker pull node:4.0
docker-compose pull
docker-compose build

$DIR/npm install
$DIR/bower install
$DIR/bower update -f