#!/usr/bin/env bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/pre-req-check
cd $DIR/..

case "$1" in
  start)
    ## NOTE: this isn't truly what prod looks like since we are hosting off github
    ## assumes docker was setup using docker-toolbox
    $DIR/sync start
    docker-compose up -d devserver
    ip=$(docker_ip)
    port=$(service_port devserver 80)
    echo "local devserver at http://${ip}:${port}"
  ;;
  stop)
    echo "stopping"
    docker-compose stop devserver
  ;;
  restart)
    $0 stop
    $0 start
  ;;
  *)
    echo "usage: $0 [start | stop | restart]"
  ;;
esac